/*
 * Copyright (c) 2013 somemetricprefix <somemetricprefix+code@gmail.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef CKFW_SRC_CORE_EVENTQUEUE_H_
#define CKFW_SRC_CORE_EVENTQUEUE_H_

#include "common.h"

// This file defines a event queue implemented with a ring buffer.
// Events are added by interrupt routines.

enum {
  // Those events are generated in by matrix.cpp
  kEventPressed,
  kEventReleased,

  // Generated by timer.cpp
  kEventTimeout,
};

struct Event {
  u8 event;

  u8 row : 4;
  u8 column : 4;
};

// Add an event to the event queue.
#ifdef __cplusplus
extern "C" void EventQueueWrite(u8 event, u8 row, u8 col);
#else
void EventQueueWrite(u8 event, u8 row, u8 col);
#endif

// Returns a pointer to an Event struct that can be read from.
struct Event EventQueueRead(void);

// Returns true if the queue is empty, false otherwise.
bool EventQueueEmpty(void);

#endif  // CKFW_SRC_CORE_EVENTQUEUE_H_
